# Generated by Django 5.1.2 on 2026-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
