# Generated by Django 5.1.2 on 2026-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_count_alter_otp_otp_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
