import factory
from mainapp.models import Notes, Product, ProductCategory, ProductVariant


class ProductCategoryFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = ProductCategory

    name = factory.Faker("word")
    parent = None
    # slug is auto-generated by ProductCategory.save()


class NoteFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Notes

    title = factory.Faker("word")
    type = "TOP_NOTE"


class ProductFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Product

    title = factory.Faker("sentence", nb_words=3)
    is_active = True
    # slug is auto-generated by Product.save()

    @factory.post_generation
    def with_variants(self, create, extracted, **kwargs):
        """Pass with_variants=True to auto-create 2 variants after product creation."""
        if create and extracted:
            ProductVariant.objects.create(
                product=self, price=999, discounted_price=899, stock=10
            )
            ProductVariant.objects.create(
                product=self, price=1999, discounted_price=1799, stock=5
            )

    @factory.post_generation
    def category(self, create, extracted, **kwargs):
        if not create or not extracted:
            return
        for cat in extracted:
            self.category.add(cat)


class ProductVariantFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = ProductVariant

    product = factory.SubFactory(ProductFactory)
    price = factory.Faker(
        "pydecimal", min_value=500, max_value=5000, right_digits=2, positive=True
    )
    discounted_price = factory.Faker(
        "pydecimal", min_value=400, max_value=4900, right_digits=2, positive=True
    )
    stock = 10
    available = True
