# Generated by Django 5.1.2 on 2026-02-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_productcategory_slug_productvariant_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='note', to='mainapp.notes'),
        ),
    ]
