# Generated by Codex on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0026_alter_review_rating_checkoutsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="awb_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="label",
        ),
        migrations.RemoveField(
            model_name="order",
            name="manifest",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_schedule_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_token_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shiprocket_invoice",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shiprocket_order_id",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="awb_code",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="label",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="manifest",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="pickup_schedule_date",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="pickup_status",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="pickup_token_number",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="shipment_id",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="shiprocket_invoice",
        ),
        migrations.RemoveField(
            model_name="returnexchange",
            name="shiprocket_order_id",
        ),
        migrations.DeleteModel(
            name="ShiprocketToken",
        ),
    ]
