# Generated by Django 5.1.2 on 2026-05-19 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_razorpay_shiprocket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cart', 'cart'), ('buynow', 'buynow')], max_length=12)),
                ('cart_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('txnid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED'), ('ABANDONED', 'ABANDONED')], default='INITIATED', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.checkoutsession')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='mainapp.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Session',
                'verbose_name_plural': 'Payment Sessions',
                'indexes': [models.Index(fields=['cart_fingerprint', 'status'], name='mainapp_pay_cart_fi_ccec50_idx')],
            },
        ),
    ]
